# Utilise une image officielle PHP avec Apache
FROM php:8.2-apache

# Installe les extensions nécessaires pour Symfony
RUN docker-php-ext-install pdo pdo_mysql

# Copie tout ton projet dans le conteneur
COPY . /var/www/html/

# Définit le dossier public/ comme racine
WORKDIR /var/www/html/

# Installe Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Installe les dépendances Symfony
RUN composer install --no-dev --optimize-autoloader

# Active mod_rewrite (important pour Symfony)
RUN a2enmod rewrite
COPY ./public/.htaccess /var/www/html/public/.htaccess

# Expose le port 80
EXPOSE 80
