services:
  - type: web
    name: symfony-app
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_DEBUG
        value: false
      - key: APP_SECRET
        generateValue: true
